Fix redaction script
uc-cdis/dcf-dataservice pull request #109
Opened 2022-06-13 15:04 UTC by MaribelleHGomez

Fix request body

Description about what this pull request does.

Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.

### New Features

### Breaking Changes

### Bug Fixes
- redaction wasn't deleting indexd records unless the gs or s3 url was still active

### Improvements

### Dependency updates

### Deployment changes

2022-07-20 14:04 UTC, BinamB requested changes

2022-07-28 12:30 UTC, MaribelleHGomez commented on scripts/deletion.py
> +            res = bucket.delete_objects(Delete={"Object": [deleting_object]})
done

2022-07-28 12:30 UTC, MaribelleHGomez commented on scripts/deletion.py
>      if not dry_run:
done

2022-08-05 14:32 UTC, BinamB approved these changes

2022-08-08 14:33 UTC, merged