(Chore): Migrate to poetry
uc-cdis/dcf-dataservice pull request #141
Opened 2024-10-09 18:43 UTC by BinamB

Description about what this pull request does.

Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.

### New Features
- Migrated dependency handling to poetry

### Breaking Changes

### Bug Fixes

### Improvements
- Added support for Glacier Instant Retreival

### Dependency updates

### Deployment changes

2024-12-18 17:47 UTC, jacob50231 approved these changes
Code looks good assuming we can get this to pass jenkins.

2024-12-18 17:47 UTC, jacob50231 commented on requirements.txt
Is there a reason we're still tracking requirements.txt after migrating to poetry?

2024-12-18 18:59 UTC, MaribelleHGomez requested changes

2024-12-18 18:59 UTC, MaribelleHGomez commented on dcfdataservice/utils.py
> +def get_indexd_record_from_GDC_files(manifest_file, logger):
is it me, or is this the same function from ln 420?

2024-12-18 19:16 UTC, MaribelleHGomez commented on requirements.txt
I believe that is still needed for the Google dataflow job

2025-01-14 15:56 UTC, BinamB commented on dcfdataservice/google_replicate.py
> +        logger.info(msg)
No, you're right. I keep forgetting to add exit `return`s

2025-01-14 15:59 UTC, BinamB commented on dcfdataservice/utils.py
> +def get_indexd_record_from_GDC_files(manifest_file, logger):
removed. Idk what i was doing

2025-01-14 16:53 UTC, MaribelleHGomez approved these changes
lgtm

2025-01-27 20:57 UTC, BinamB commented on requirements.txt
Yeah its a different requirements file thats supposed to provide the dependencies for the google dataflow job. The poetry toml installs the dependencies on the kubernetes job and the kubernetes job initiates a google job which uses the requriements.txt

2025-02-17 17:44 UTC, jacob50231 approved these changes
I was able to fix the snyk issue and we were able to get it tested on a dev environment. Everything is looking good!

2025-02-20 15:10 UTC, jacob50231 approved these changes

2025-02-20 15:11 UTC, merged